//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaFinalApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDishes = new HashSet<OrderDish>();
        }

        public int Id { get; set; }
        public int StatusId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
        [NotMapped]
        public string FullName => $"{User.LastName} {User.FirstName} {User.MiddleName}";
        [NotMapped]
        public string Composition => string.Join(",", OrderDishes.Select(od => $" {od.Amount}x{od.Dish.Name}({od.SelectedDishSize} см)"));
        [NotMapped]
        public float TotalCost => OrderDishes.Sum(o => o.DishCost);


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDish> OrderDishes { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual User User { get; set; }
    }
}
