//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaFinalApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class OrderDish
    {
        public int Id { get; set; }
        public int DishId { get; set; }
        public int Amount { get; set; }
        public int SelectedDishSize { get; set; }
        public int OrderId { get; set; }
        [NotMapped]
        public float DishCost => Amount * Dish.Price;
    
        public virtual Dish Dish { get; set; }
        public virtual Order Order { get; set; }
    }
}
