//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaFinalApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Size
    {
        public int Id { get; set; }
        public int DishId { get; set; }
        public int Size1 { get; set; }
        public int Price { get; set; }
        public int Weight { get; set; }
        [NotMapped]
        public int DishAmount { get; set; } = 0;

        public virtual Dish Dish { get; set; }
    }
}
